### ISSUE TITLE
Can't use Astro files anymore, neovim completely crashes when astro Treesitter is installed

### ISSUE THREAD

**Issue by bastianhenneberg** [virchau13/tree-sitter-astro#26] opened 2024-04-16 07:46 UTC
My Neovim is crashing with a SEGV Error when astro is installed in Treesitter after typing one or two characters. 
When i Uninstall astro in Treesitter everything works fine but i have no highlights.

My Neovim Version is 0.9.5 i have tested on two separate Computers with Linux installed. On Friday everything worked fine, the problem occured yesterday evening. I have updated everything and also reinstalled all Plugins, Neovim and Node. But the error is still present.

**Comment by TunkShif** [comment] 2024-04-17 07:38
Can confirm, had the same issue using Neovim 0.9.5 and the latest version of treesitter.
And it seems that I can't find any related logs.

https://github.com/virchau13/tree-sitter-astro/assets/10807119/77717c3c-4371-4915-a807-ab4a6095b4a1

**Comment by virchau13** [comment] 2024-04-19 07:39
I can't reproduce this issue. If you attach `gdb` to neovim and check the `backtrace` after it SEGVs, what happens?

**Comment by tendertree** [comment] 2024-04-19 08:36
same thing happens 
NVIM v0.9.5
it occur when 

`highlight = { enable = true}`

in my case  when I type some html tag
<div> <p> .. <h1> 
and suddenly neovim is closed

only way to solve is delete tree-sitter-astro or disable highilght

**Comment by virchau13** [comment] 2024-04-19 08:41
If you try neovim nightly, does it fix the issue?

**Comment by bastianhenneberg** [comment] 2024-04-19 08:48
Neovim nightly dosen't help for me tested it on Arch Linux with the AUR nightly build

**Comment by tendertree** [comment] 2024-04-19 10:36
https://github.com/virchau13/tree-sitter-astro/assets/3841867/45a650e5-9693-4638-a509-84f1912676d6



I changed neovim nightly, but doesn't fix the problem
this is my situation
when I type <div> . neovim closed immediately

**Comment by virchau13** [comment] 2024-04-19 11:33
I may have fixed the issue with the above commit, but I'm not sure. Can someone help test it?

To test:
1. Git clone tree-sitter-astro somewhere (e.g. `/tmp/tree-sitter-astro`).
2. Add the following to your neovim configuration:
```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.astro.install_info.url = "/tmp/tree-sitter-astro" -- replace this path with where you cloned it to
```
3. Open neovim and run `:TSInstall astro`.
4. Try causing the crash again.

**Comment by tendertree** [comment] 2024-04-19 13:18
I follwed  above commit, it work out of box 👍

**Comment by virchau13** [comment] 2024-04-19 13:46
I'm fairly sure this issue is the same as https://github.com/tree-sitter/tree-sitter-html/commit/de9379515537d9b43b7aaf5a72681ae37beafd55 and is fixed, so I'm going to close this.

The fix should be available on mainstream nvim-treesitter in about 18 hours: run `:TSUpdate` after that to get the new version. If you want to fix it now, use [the above method](https://github.com/virchau13/tree-sitter-astro/issues/26#issuecomment-2066384630).

If this doesn't fix it, please comment.

**Closed by virchau13** 2024-04-19 13:46 UTC

**Comment by ecruzolivera** [comment] 2024-05-14 17:43
Hello, I'm getting this exact issue

**Comment by virchau13** [comment] 2024-05-15 13:05
@ecruzolivera Does updating the nvim-treesitter plugin and re-running `:TSUpdate` fix it?

**Comment by ecruzolivera** [comment] 2024-05-20 07:04
> @ecruzolivera Does updating the nvim-treesitter plugin and re-running `:TSUpdate` fix it?

I tried several things, including that, and it kept crashing, then because I'm using the astronvim distribution i created a minimal nvim with astro TS and astro lsp and it worked just fine. Today I updated nvim plugins, lsp, TS, etc, and i it worked.
